Auto-publish to Anaconda
TileDB-Inc/r-shinybg-feedstock pull request #6
Opened 2024-06-10 20:29 UTC by johnkerl

Per @jdblischak

2024-06-10 20:33 UTC, jdblischak requested changes
Since we use internal branches, you should add `upload_on_branch: main` to `conda-forge.yml` (and rerender), just like we do in [tiledbsoma-feedstock](https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/a44ad933e5fea433a2810f3a716a7868d9984bff/conda-forge.yml#L10)

2024-06-10 20:52 UTC, johnkerl commented
2nd commit was:

```
mamba upgrade -c conda-forge conda-smithy -n base
conda smithy rerender --commit auto
```

2024-06-10 21:15 UTC, jdblischak approved these changes

2024-06-11 13:32 UTC, ihnorton approved these changes

2024-06-11 13:34 UTC, merged